include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    use_super_parameters: true
    sort_child_properties_last: true
    avoid_print: true
